load(":defs.bzl", "deb_tool_bundle", "python_runtime")

package(default_visibility = ["//visibility:public"])

exports_files(["prepare_deb_tools.py"])

python_runtime(name = "python_runtime")

deb_tool_bundle(
    name = "sai_generator_tools",
    architecture = select({
        "@platforms//cpu:x86_64": "amd64",
        "@platforms//cpu:aarch64": "arm64",
    }),
    debs = select({
        "@platforms//cpu:x86_64": ["@sairedis_generator_tools_amd64//:debs"],
        "@platforms//cpu:aarch64": ["@sairedis_generator_tools_arm64//:debs"],
    }),
)
