#!/bin/bash

STABLE_SAIREDIS_GIT_REVISION=$(git rev-parse --short HEAD || echo 0000000)
STABLE_SAI_GIT_REVISION=$(cd ./SAI && git rev-parse --short HEAD || echo 0000000)
echo "STABLE_SAIREDIS_GIT_REVISION ${STABLE_SAIREDIS_GIT_REVISION}"
echo "STABLE_SAI_GIT_REVISION ${STABLE_SAI_GIT_REVISION}"
