load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("//bazel:common.bzl", "CODE_COVERAGE_LINKOPTS", "GTEST_DEPS", "TEST_COPTS", "VPP_DEPS", "working_directory_test")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "source_files",
    srcs = glob([
        "*.cpp",
        "*.h",
        "*.am",
        "*.json",
        "*.ini",
        "files/**",
    ]),
)

cc_binary(
    name = "tests_binary",
    testonly = True,
    srcs = [
        "MockHelper.cpp",
        "MockableSaiInterface.cpp",
        "MockableSaiSwitchInterface.cpp",
        "TestAttrVersionChecker.cpp",
        "TestBestCandidateFinder.cpp",
        "TestCommandLineOptions.cpp",
        "TestConcurrentQueue.cpp",
        "TestFlexCounter.cpp",
        "TestFlowDump.cpp",
        "TestMdioIpcServer.cpp",
        "TestMySidWarmboot.cpp",
        "TestNotificationHandler.cpp",
        "TestNotificationProcessor.cpp",
        "TestNotificationQueue.cpp",
        "TestPortPhyAttr.cpp",
        "TestPortPhySerdesAttr.cpp",
        "TestPortStateChangeHandler.cpp",
        "TestSelectablesTracker.cpp",
        "TestSyncd.cpp",
        "TestTimerWatchdog.cpp",
        "TestVendorSai.cpp",
        "TestVirtualOidTranslator.cpp",
        "TestWorkaround.cpp",
        "main.cpp",
    ] + glob(["*.h"]),
    copts = TEST_COPTS + ["-fno-access-control"],
    includes = ["."],
    linkopts = ["-pthread"] + CODE_COVERAGE_LINKOPTS,
    tags = ["manual"],
    deps = [
        "//lib:sairedis_shared",
        "//meta:saimeta_shared",
        "//syncd:libmdio_ipc_client.a",
        "//syncd:libsyncd",
        "//syncd:libsyncd_request_shutdown",
        "//vslib:saivs.a",
        "@sonic_swss_common//:libswsscommon_shared",
    ] + GTEST_DEPS + VPP_DEPS,
)

working_directory_test(
    name = "tests",
    data = glob([
        "*.json",
        "*.ini",
        "files/**",
    ]),
    program = ":tests_binary",
    tags = [
        "exclusive",
        "manual",
        "requires-cap-dac-override",
        "requires-cap-ipc-lock",
        "requires-cap-ipc-owner",
        "requires-cap-sys-time",
        "requires-redis",
    ],
    working_directory = "unittest/syncd",
)
